### ISSUE TITLE
Mounting parent component in tests throws error

### ISSUE THREAD

**Issue by 00george** [RIP21/react-simplemde-editor#147]
Hi I am mounting a parent component which contains a child component which contains the react-simplemde-editor however in tests I get:
`
    at SimpleMDEEditor.addEvents (node_modules/react-simplemde-editor/src/index.tsx:156:33)
    at SimpleMDEEditor.componentDidMount (node_modules/react-simplemde-editor/src/index.tsx:79:12)
    at commitLifeCycles (node_modules/react-dom/cjs/react-dom.development.js:19814:22)
    at commitLayoutEffects (node_modules/react-dom/cjs/react-dom.development.js:22803:7)
    at HTMLUnknownElement.callCallback (node_modules/react-dom/cjs/react-dom.development.js:188:14)
    at HTMLUnknownElement.callTheUserObjectsOperation (node_modules/jsdom/lib/jsdom/living/generated/EventListener.js:26:30)
      at innerInvokeEventListeners (node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:318:25)
      at invokeEventListeners (node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:274:3)
      at HTMLUnknownElementImpl._dispatch (node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:221:9)
      at HTMLUnknownElementImpl.dispatchEvent (node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:94:17)
      at HTMLUnknownElement.dispatchEvent (node_modules/jsdom/lib/jsdom/living/generated/EventTarget.js:231:34)
      at Object.invokeGuardedCallbackDev (node_modules/react-dom/cjs/react-dom.development.js:237:16)
      at invokeGuardedCallback (node_modules/react-dom/cjs/react-dom.development.js:292:31)
      at commitRootImpl (node_modules/react-dom/cjs/react-dom.development.js:22541:9)
      at unstable_runWithPriority (node_modules/scheduler/cjs/scheduler.development.js:653:12)
      at runWithPriority$1 (node_modules/react-dom/cjs/react-dom.development.js:11039:10)
      at commitRoot (node_modules/react-dom/cjs/react-dom.development.js:22381:3)
      at finishSyncRender (node_modules/react-dom/cjs/react-dom.development.js:21807:3)
      at performSyncWorkOnRoot (node_modules/react-dom/cjs/react-dom.development.js:21793:7)
      at node_modules/react-dom/cjs/react-dom.development.js:11089:24
`
Does anyone know how to fix this? I am using the latest version.

**Comment by RIP21** [comment]
It's been a while :) But with version `5.0.0` it works for sure no problem (maybe it even worked with old one). But with `@testing-library/react`
Here is how I do it
```tsx
import {act, render, screen} from "@testing-library/react";
import { useState } from "react";
import { SimpleMdeReact } from "SimpleMdeReact";
import userEvent from "@testing-library/user-event";

// @ts-ignore
Document.prototype.createRange = function () {
  return {
    setEnd: function () {},
    setStart: function () {},
    getBoundingClientRect: function () {
      return { right: 0 };
    },
    getClientRects: function () {
      return {
        length: 0,
        left: 0,
        right: 0,
      };
    },
  };
};

const Editor = () => {
  const [value, setValue] = useState("");
  return <SimpleMdeReact value={value} onChange={setValue} />;
};

describe("Renders", () => {
  it("succesfully", async () => {
    act(() => {
      render(<Editor />);
    });
    const editor = await screen.findByRole("textbox");
    userEvent.type(editor, "hello")
    expect(screen.getByText('hello')).toBeDefined()
  });
});
```

It requires polyfills  so you need to add it. This `Document.prototype.createRange = function () {` line and onwards
