### ISSUE TITLE
Unable to render component from jest

### ISSUE THREAD

**Issue by Furiens** [RIP21/react-simplemde-editor#77]
I have a simple typescript react application using webpack, created with create-react-app. SimpleMDEEditor works fine in the browser, but if I render it in a jest test, it throws the following exception:

`
    TypeError: Cannot read property 'getElementsByClassName' of null
      at SimpleMDEEditor._this.addEvents (node_modules/react-simplemde-editor/lib/index.js:97:34)
      at SimpleMDEEditor.componentDidMount (node_modules/react-simplemde-editor/lib/index.js:147:14)
      at commitLifeCycles (node_modules/react-dom/cjs/react-dom.development.js:14685:22)
      at commitAllLifeCycles (node_modules/react-dom/cjs/react-dom.development.js:15905:7)
      at HTMLUnknownElement.callCallback (node_modules/react-dom/cjs/react-dom.development.js:145:14)
      at invokeEventListeners (node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:193:27)
      at HTMLUnknownElementImpl._dispatch (node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:119:9)
      at HTMLUnknownElementImpl.dispatchEvent (node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:82:17)
      at HTMLUnknownElementImpl.dispatchEvent (node_modules/jsdom/lib/jsdom/living/nodes/HTMLElement-impl.js:30:27)
      at HTMLUnknownElement.dispatchEvent (node_modules/jsdom/lib/jsdom/living/generated/EventTarget.js:157:21)
      at Object.invokeGuardedCallbackDev (node_modules/react-dom/cjs/react-dom.development.js:195:16)
      at invokeGuardedCallback (node_modules/react-dom/cjs/react-dom.development.js:248:31)
      at commitRoot (node_modules/react-dom/cjs/react-dom.development.js:16075:7)
      at completeRoot (node_modules/react-dom/cjs/react-dom.development.js:17463:3)
      at performWorkOnRoot (node_modules/react-dom/cjs/react-dom.development.js:17391:9)
      at performWork (node_modules/react-dom/cjs/react-dom.development.js:17295:7)
      at performSyncWork (node_modules/react-dom/cjs/react-dom.development.js:17267:3)
      at requestWork (node_modules/react-dom/cjs/react-dom.development.js:17155:5)
      at scheduleWork (node_modules/react-dom/cjs/react-dom.development.js:16949:5)
      at scheduleRootUpdate (node_modules/react-dom/cjs/react-dom.development.js:17637:3)
      at updateContainerAtExpirationTime (node_modules/react-dom/cjs/react-dom.development.js:17664:10)
      at updateContainer (node_modules/react-dom/cjs/react-dom.development.js:17691:10)
      at ReactRoot.Object.<anonymous>.ReactRoot.render (node_modules/react-dom/cjs/react-dom.development.js:17957:3)
      at node_modules/react-dom/cjs/react-dom.development.js:18097:14
      at unbatchedUpdates (node_modules/react-dom/cjs/react-dom.development.js:17518:10)
      at legacyRenderSubtreeIntoContainer (node_modules/react-dom/cjs/react-dom.development.js:18093:5)
      at Object.render (node_modules/react-dom/cjs/react-dom.development.js:18152:12)
      at Object.<anonymous> (src/MyComponent.test.tsx:32:18)
`

**Comment by RIP21** [comment]
Try to use `mount` if you use an `enzyme` for testing.  
This module heavily relies on Web API and DOM elements itself, since it's just a wrapper around `simplemde` editor which is not using any library such as `React` but pure JS to control stuff.
So it may be a tricky thing to make it run in a the unit test environment.
You can test it easily using `cypress` which is an amazing tool for `e2e` testing IN the browser itself. 

If anyone can give more insights, will be glad.

**Comment by RIP21** [comment]
I forgot to mention that you would need to have `jsdom` for it to be tested I think.

**Comment by Etlas** [comment]
I'm having this issue as well. And I think I can elaborate a little bit.
I have a wrapper component for the editor. Testing this wrapper component with enzyme seems to work just fine.

But then I use this wrapper component inside of other components. Testing those with enzyme causes the same errors above.

**Comment by RIP21** [comment]
I'll deploy in a minute a new version with the fix of @Etlas hope it will help.
